name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  armv7_job:
    # The host should always be Linux
    runs-on: ubuntu-18.04
    name: arch64
    steps:
      - uses: actions/checkout@v2.1.0

      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: bullseye

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}
          
          # Mount the artifacts directory as /artifacts in the container
          dockerRunArgs: |
            --volume "${PWD}:/artifacts"
            
          # The shell to run commands with in the container
          shell: /bin/sh
          
          install: |
            apt update -y

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            uname -a
            set -e
            export APT_LISTCHANGES_FRONTEND=none
            export DEBIAN_FRONTEND=noninteractive
            cd /artifacts/
            echo Install dependencies.
            apt-get update -y
            apt-get install --allow-change-held-packages --allow-downgrades --allow-remove-essential -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold -fy wget

      - name: Show the artifact
        run: |
          ls -la
          
