name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  armv7_job:
    # The host should always be Linux
    runs-on: ubuntu-18.04
    name: Build on ubuntu-18.04 armv7
    steps:
      - uses: actions/checkout@v2.1.0
      
      - name: Show folder content
        run: |
          ls -la

      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: bullseye

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}
          
           # Create an artifacts directory
          setup: |
            mkdir -p "${PWD}/artifacts"
          
          # Mount the artifacts directory as /artifacts in the container
          dockerRunArgs: |
            --volume "${PWD}:/artifacts"
            
          # The shell to run commands with in the container
          shell: /bin/sh
          
          install: |
            cd /artifacts/
            echo "hello"
            ls -la

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            uname -a
            echo "Produced artifact" >> /artifacts/buildlog.txt

      - name: Show the artifact
        run: |
          ls -la
          
