name: build
on:
  schedule:
  - cron: '0 */12 * * *'
  push:
    branches: [ main ]
    paths: 
      - '**.sh'
      - Dockerfile
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: armv7
          distro: ubuntu18.04
          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)
        
      - name: Build
        uses: ./
      - name: Upload
        uses: actions/upload-artifact@v3.0.0
        with:
          name: v4.${{ env.minor }}.${{ env.patch }}
          path: /home/runner/work/_temp/_github_home/nginx.deb
      - name: Update
        if: ${{ env.change }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update hash and version
      - name: Release
        if: ${{ env.change }}
        uses: softprops/action-gh-release@v1
        with:
          files: /home/runner/work/_temp/_github_home/nginx.deb
          body: "SHA256: ${{ env.hash }}"
          tag_name: v4.${{ env.minor }}.${{ env.patch }}
          generate_release_notes: false
